apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: random-logger
  name: random-logger
spec:
  replicas: 1
  selector:
    matchLabels:
      app: random-logger
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: random-logger
    spec:
      containers:
      - image: chentex/random-logger
        name: random-logger
        resources: {}
status: {}
