apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: redis-master
  name: redis-master
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: redis:latest
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: "" 
