apiVersion: v1
kind: DeploymentConfig
metadata:
  annotations:
    kompose.cmd: kompose --provider openshift convert
    kompose.version: 1.9.0 (093c756)
  creationTimestamp: null
  labels:
    io.kompose.service: redis-slave
  name: redis-slave
spec:
  replicas: 1
  selector:
    io.kompose.service: redis-slave
  strategy:
    resources: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: redis-slave
    spec:
      containers:
      - env:
        - name: GET_HOSTS_FROM
          value: dns
        image: ' '
        name: redis-slave
        ports:
        - containerPort: 6379
        resources: {}
      restartPolicy: Always
  test: false
  triggers:
  - type: ConfigChange
  - imageChangeParams:
      automatic: true
      containerNames:
      - redis-slave
      from:
        kind: ImageStreamTag
        name: redis-slave:v1
    type: ImageChange
status: {}
